version: '3.8'

services:
    # PHP Application (Laravel)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: drono-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_DATABASE=drono_db
            - DB_USERNAME=drono_user
            - DB_PASSWORD=secret

    # Nginx Web Server
    nginx:
        image: nginx:latest
        container_name: drono-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    # PostgreSQL Database
    db:
        image: postgres:15
        container_name: drono-db
        environment:
            - POSTGRES_DB=drono_db
            - POSTGRES_USER=drono_user
            - POSTGRES_PASSWORD=secret
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    # Node.js for React.js (optional for dev builds)
    node:
        image: node:18
        container_name: drono-node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: ["npm", "run", "dev"]

volumes:
    dbdata:
